version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/edupago?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - edupago-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: edupago
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - edupago-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - edupago-network

networks:
  edupago-network:
    driver: bridge
